# Generated by Django 3.1 on 2021-07-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='org',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
