# Generated by Django 3.1 on 2021-07-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='invite_code',
            field=models.TextField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
